

  boot:
    admin:
      client:
        url:
        - http://localhost:9494

  instance:
    hostname: loacalhost
    prefer-ip-address: true 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  
        
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true   
      
  endpoints:
    web:
      exposure:
        include:
        - "*"      
